spring.application.name=management-system
spring.datasource.url=jdbc:mysql://localhost:3306/hostel_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Test@1234!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
